# Generated by Django 5.0.1 on 2025-11-28 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_template_id', models.CharField(blank=True, help_text='Railway Template ID', max_length=255, null=True)),
                ('railway_workspace_id', models.CharField(blank=True, help_text='Railway Workspace ID', max_length=255, null=True)),
                ('railway_token', models.CharField(blank=True, help_text='Railway API Token', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='railway_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Railway Settings',
                'verbose_name_plural': 'Railway Settings',
            },
        ),
    ]
