# Generated by Django 4.2.14 on 2025-11-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(help_text='Service identifier (e.g., service_1)', max_length=255)),
                ('name', models.CharField(default='New Service', help_text='Service name', max_length=255)),
                ('image', models.CharField(blank=True, help_text='Docker image or source', max_length=500, null=True)),
                ('cpu', models.IntegerField(default=8, help_text='CPU allocation')),
                ('memory', models.IntegerField(default=8, help_text='Memory in GB')),
                ('variables', models.JSONField(default=dict, help_text='Environment variables')),
                ('networking', models.JSONField(default=dict, help_text='Networking configuration')),
                ('position_x', models.FloatField(default=0, help_text='X position on canvas')),
                ('position_y', models.FloatField(default=0, help_text='Y position on canvas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.template')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['created_at'],
                'unique_together': {('template', 'service_id')},
            },
        ),
    ]
