# Generated by Django 4.2.14 on 2025-11-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='registry_password',
            field=models.CharField(blank=True, help_text='Docker registry password (encrypted)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='registry_username',
            field=models.CharField(blank=True, help_text='Docker registry username', max_length=255, null=True),
        ),
    ]
