# Generated by Django 4.2.14 on 2025-11-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_service_registry_password_service_registry_username'),
    ]

    operations = [
        # First rename the model
        migrations.RenameModel(
            old_name='Service',
            new_name='TemplateService',
        ),
        # Then alter its options
        migrations.AlterModelOptions(
            name='templateservice',
            options={'ordering': ['created_at'], 'verbose_name': 'Template Service', 'verbose_name_plural': 'Template Services'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='railway_template_id',
        ),
        migrations.AddField(
            model_name='template',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this template has been published to Railway'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Project description', null=True)),
                ('railway_project_id', models.CharField(blank=True, help_text='Railway Project ID', max_length=255, null=True)),
                ('railway_environment_id', models.CharField(blank=True, help_text='Railway Environment ID', max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', help_text='Deployment status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is active')),
                ('deployed_at', models.DateTimeField(blank=True, help_text='When the project was deployed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_template', models.ForeignKey(blank=True, help_text='Template this project was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_projects', to='accounts.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(help_text='Service identifier (e.g., service_1)', max_length=255)),
                ('name', models.CharField(default='New Service', help_text='Service name', max_length=255)),
                ('railway_service_id', models.CharField(blank=True, help_text='Railway Service ID', max_length=255, null=True)),
                ('railway_deployment_id', models.CharField(blank=True, help_text='Railway Deployment ID', max_length=255, null=True)),
                ('image', models.CharField(blank=True, help_text='Docker image or source', max_length=500, null=True)),
                ('registry_username', models.CharField(blank=True, help_text='Docker registry username', max_length=255, null=True)),
                ('registry_password', models.CharField(blank=True, help_text='Docker registry password (encrypted)', max_length=500, null=True)),
                ('cpu', models.IntegerField(default=8, help_text='CPU allocation')),
                ('memory', models.IntegerField(default=8, help_text='Memory in GB')),
                ('variables', models.JSONField(default=dict, help_text='Environment variables')),
                ('networking', models.JSONField(default=dict, help_text='Networking configuration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('deploying', 'Deploying'), ('running', 'Running'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', help_text='Service status', max_length=20)),
                ('public_url', models.URLField(blank=True, help_text='Public URL if networking is enabled', null=True)),
                ('position_x', models.FloatField(default=0, help_text='X position on canvas')),
                ('position_y', models.FloatField(default=0, help_text='Y position on canvas')),
                ('deployed_at', models.DateTimeField(blank=True, help_text='When the service was deployed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.project')),
                ('source_service', models.ForeignKey(blank=True, help_text='Template service this was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_services', to='accounts.templateservice')),
            ],
            options={
                'verbose_name': 'Project Service',
                'verbose_name_plural': 'Project Services',
                'ordering': ['created_at'],
                'unique_together': {('project', 'service_id')},
            },
        ),
    ]
